name: Nightly build

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/create-nightly-build.yaml'
      - 'process_files.py'
      - 'datapacks/**'

permissions:
  contents: write

env:
  NIGHTLY_TAG: "nightly"
  NIGHTLY_NAME: "nightly"
  NIGHTLY_BODY: "This is an automatic nightly release. It may have changes that are not fully tested."

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v6.0.2

    - uses: actions/setup-python@v6.2.0
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install pandas openpyxl

    - name: Process files
      run: make

    - name: Compress datapack(s)
      run: |
        zip -r ./datapacks/CobblemonJohto.zip ./datapacks/CobblemonJohto

    - name: Create release zip
      run: |
        zip -r johto-cobblemon.zip ./datapacks/CobblemonJohto.zip ./data ./serverconfig
    
    - name: Update nightly tag
      run: |
        git tag $NIGHTLY_TAG -f
        git push origin $NIGHTLY_TAG -f

    - name: Create release if it doesn't exist
      run: |
        gh release view $NIGHTLY_TAG || gh release create $NIGHTLY_TAG --title "$NIGHTLY_NAME" --notes "$NIGHTLY_BODY"
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload release assets
      run: |
        gh release upload $NIGHTLY_TAG johto-cobblemon.zip --clobber
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}